apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcp-website-fetcher.yaml
  - test-kmcp-server.yaml
  - kubagent.yaml
  - agent-k8s-simple.yaml
  - agent-fetch.yaml
  - support_agent.yaml
